name: niva
description: Hair and Beauty App


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  dots_indicator: ^2.0.0

  get: ^4.1.4

  

  


  cupertino_icons: ^1.0.2


auto_size_text: ^3.0.0
built_collection: ^5.2.0
built_value: ^8.1.0
cached_network_image: ^3.2.0
chewie: ^1.4.0
cloud_firestore: ^2.5.4
firebase_auth: ^3.3.6
firebase_core: ^3.1.6
flutter_animate: ^1.0.0
flutter_cache_manager: ^4.2.0
flutter_spinkit: ^6.2.0
flutter_staggered_grid_view: ^0.4.0
font_awesome_flutter: ^9.1.0
google_fonts: ^2.1.0
google_sign_in: ^5.2.1
intl: ^0.17.0
json_path: ^0.5.3
json_serializable: ^6.3.0
page_transition: ^2.0.8
provider: ^6.2.0
rxdart: ^0.27.3
shared_preferences: ^2.0.16
sign_in_with_apple: ^3.0.0
simple_gradient_text: ^1.2.3
smooth_page_indicator: ^2.0.0
sqflite: ^2.0.0+3
timeago: ^4.0.0
url_launcher: ^6.0.10
video_player: ^2.2.5




dev_dependencies:
  flutter_test:
    sdk: flutter


  
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true




